name: HEIG-VD DAI GitHub Workflow

# Allow one concurrent deployment
concurrency:
  group: GitHub Pages
  cancel-in-progress: true

on:
  push:
    # branches:
    #   - main
    # tags:
    #   - "*"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages and to release to GitHub Releases
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-upload-course-presentations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build presentations with Marp
        uses: docker://marpteam/marp-cli:v4.1.1
        with:
          entrypoint: sh
          args: build-all-presentations.sh

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: course-presentations
          path: |
            **/*.jpg
            **/*.jpeg
            **/*.png
            **/*.svg
            **/*-presentation.pdf
            **/index.html
          if-no-files-found: error
          retention-days: 1

  create-index-page-for-github-pages:
    runs-on: ubuntu-latest
    needs: build-and-upload-course-presentations
    steps:
      - name: Download course presentations
        uses: actions/download-artifact@v4
        with:
          name: course-presentations

      - name: Install packages
        run: sudo apt install --yes tree

      - name: Generate index.html with tree
        run: |
          tree -H '.' --noreport --dirsfirst -T 'HEIG-VD DAI Course' -P "*.html" --prune --charset utf-8 -o index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  publish-course-presentations-to-github-pages:
    needs: create-index-page-for-github-pages
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-github-release:
    runs-on: ubuntu-latest
    needs: build-and-upload-course-presentations
    # TODO: Remove this
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Download course presentations
        uses: actions/download-artifact@v4
        with:
          name: course-presentations

      - name: Release course material to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          body: |
            This is a new release for the [Développement d'applications internet (DAI)](https://gaps.heig-vd.ch/consultation/fiches/uv/uv.php?id=6573) course at [HEIG-VD](https://heig-vd.ch), Switzerland!

            Access the Git files using the commit SHA [${{ github.sha }}](TODO)
          files: |
            **/*-presentation.pdf
